<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dependability" nsURI="http://www.deis-project.eu/ode/dependability"
    nsPrefix="dependability_">
  <eClassifiers xsi:type="ecore:EClass" name="MaintenanceProcedure" eSuperTypes="odeBase.ecore#//BaseElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="activityDescription" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="technicalDescription" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="toolSpecification" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="staffNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="staffSkillLevel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="staffTrainingDescription"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MeasureType" eSuperTypes="odeBase.ecore#//BaseElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Measure" eSuperTypes="odeBase.ecore#//BaseElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="intrinsicSafety" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="safeGuard" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="applierInformation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="riskAcceptability" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="furtherAction" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="measureType" eType="#//MeasureType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assuranceLevel" eType="#//AssuranceLevel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaultToleranceMeasure" eSuperTypes="#//Measure"/>
  <eClassifiers xsi:type="ecore:EClass" name="DependabilityPackage" eSuperTypes="integration.ecore#//ODEProductPackage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="measures" upperBound="-1"
        eType="#//Measure" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="measureTypes" upperBound="-1"
        eType="#//MeasureType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="maintenanceProcedures"
        upperBound="-1" eType="#//MaintenanceProcedure" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="HARAPackages" upperBound="-1"
        eType="#//HARAPackage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirementPackages" upperBound="-1"
        eType="#//RequirementPackage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domainPackages" upperBound="-1"
        eType="#//DomainPackage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TARAPackages" upperBound="-1"
        eType="#//TARAPackage" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HARAPackage" eSuperTypes="integration.ecore#//ODEProductPackage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hazards" upperBound="-1"
        eType="#//Hazard" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hazardTypes" upperBound="-1"
        eType="#//HazardType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hazardTypeSystems" upperBound="-1"
        eType="#//HazardTypeSystem" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="malfunctions" upperBound="-1"
        eType="#//Malfunction" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="riskAssessments" upperBound="-1"
        eType="#//RiskAssessment" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="riskParameters" upperBound="-1"
        eType="#//RiskParameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Hazard" eSuperTypes="odeBase.ecore#//BaseElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="failures" upperBound="-1"
        eType="ecore:EClass failureLogic.ecore#//Failure"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="measures" upperBound="-1"
        eType="#//Measure"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hazardType" eType="#//HazardType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HazardTypeSystem" eSuperTypes="odeBase.ecore#//BaseElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hazardTypes" upperBound="-1"
        eType="#//HazardType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HazardType" eSuperTypes="odeBase.ecore#//BaseElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Malfunction" eSuperTypes="odeBase.ecore#//BaseElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hazards" upperBound="-1"
        eType="#//Hazard"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RiskAssessment" eSuperTypes="odeBase.ecore#//BaseElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relatedStandard" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="riskParameters" upperBound="-1"
        eType="#//RiskParameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hazard" eType="#//Hazard"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RiskParameter" eSuperTypes="odeBase.ecore#//BaseElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="argument" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Situation" eSuperTypes="#//RiskParameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="likelihood" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Accident" eSuperTypes="#//RiskParameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="severity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperatorMeasure" eSuperTypes="#//RiskParameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="controlability" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequirementPackage" eSuperTypes="integration.ecore#//ODEProductPackage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirementSources" upperBound="-1"
        eType="#//RequirementSource" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependabilityRequirements"
        upperBound="-1" eType="#//DependabilityRequirement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequirementSource" abstract="true" eSuperTypes="odeBase.ecore#//BaseElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="LegalContract" eSuperTypes="#//RequirementSource"/>
  <eClassifiers xsi:type="ecore:EClass" name="DependabilityRequirement" abstract="true"
      eSuperTypes="odeBase.ecore#//BaseElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="decompositionArgument"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refinedRequirements" upperBound="-1"
        eType="#//DependabilityRequirement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirementSource" eType="#//RequirementSource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="measures" upperBound="-1"
        eType="#//Measure"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="failures" upperBound="-1"
        eType="ecore:EClass failureLogic.ecore#//Failure"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assuranceLevel" eType="#//AssuranceLevel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="maintenanceProcedures"
        upperBound="-1" eType="#//MaintenanceProcedure"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SafetyRequirement" eSuperTypes="#//DependabilityRequirement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="failureReactionTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="failureDetectionTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="failureLatencyTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isSafetyGoal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hazards" upperBound="-1"
        eType="#//Hazard"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SecurityRequirement" eSuperTypes="#//DependabilityRequirement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="securityCapabilities" upperBound="-1"
        eType="#//SecurityCapability"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainPackage" eSuperTypes="integration.ecore#//ODEProductPackage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="standards" upperBound="-1"
        eType="#//Standard" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assuranceLevels" upperBound="-1"
        eType="#//AssuranceLevel" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Standard" eSuperTypes="odeBase.ecore#//BaseElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="AssuranceLevel" eSuperTypes="odeBase.ecore#//BaseElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="SafetyStandard" eSuperTypes="#//Standard">
    <eStructuralFeatures xsi:type="ecore:EReference" name="assuranceLevels" upperBound="-1"
        eType="#//AssuranceLevel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SecurityApplicationType">
    <eLiterals name="Preventive"/>
    <eLiterals name="Active" value="1"/>
    <eLiterals name="Passive" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FinancialCostType">
    <eLiterals name="USD"/>
    <eLiterals name="EUR" value="1"/>
    <eLiterals name="GBP" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OperationalCostType">
    <eLiterals name="Workhours"/>
    <eLiterals name="Workdays" value="1"/>
    <eLiterals name="Workmonths" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TARAPackage" eSuperTypes="integration.ecore#//ODEProductPackage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="identifiedRisks" upperBound="-1"
        eType="#//SecurityRisk" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="controls" upperBound="-1"
        eType="#//SecurityControl" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="consideredAssets" upperBound="-1"
        eType="#//Asset" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="consideredThreatAgents"
        upperBound="-1" eType="#//ThreatAgent" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Asset" eSuperTypes="odeBase.ecore#//BaseElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="financialValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="financialCostType" eType="#//FinancialCostType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operationalCost" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operationalCostType" eType="#//OperationalCostType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SecurityControl" eSuperTypes="#//Measure">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="category" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//SecurityApplicationType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vulnerabilities" upperBound="-1"
        eType="#//Vulnerability"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SecurityCapability" eSuperTypes="odeBase.ecore#//BaseElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="category" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//SecurityApplicationType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="implementedBy" upperBound="-1"
        eType="#//SecurityControl"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Vulnerability" eSuperTypes="odeBase.ecore#//BaseElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="category" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VulnerableItem" eSuperTypes="#//Asset">
    <eStructuralFeatures xsi:type="ecore:EReference" name="vulnerabilities" upperBound="-1"
        eType="#//Vulnerability" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttackerGoal" eSuperTypes="odeBase.ecore#//BaseElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="category" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="addressedBy" upperBound="-1"
        eType="#//SecurityCapability" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attacks" upperBound="-1"
        eType="#//Attack" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attackedItems" upperBound="-1"
        eType="#//VulnerableItem"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SecurityRisk" eSuperTypes="odeBase.ecore#//BaseElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="likelihood" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="impactAsset" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="impactIndividuals" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="impactBusiness" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attackerGoals" upperBound="-1"
        eType="#//AttackerGoal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attack" eSuperTypes="odeBase.ecore#//BaseElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="category" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="financialCost" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="financialCostType" eType="#//FinancialCostType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeRequired" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeUnit" eType="ecore:EEnum odeBase.ecore#//TimeUnit"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="difficulty" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="detectability" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="violations" upperBound="-1"
        eType="ecore:EClass failureLogic.ecore#//SecurityViolation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exploitedVulnerabilities"
        upperBound="-1" eType="#//Vulnerability"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Payload" eSuperTypes="#//Attack"/>
  <eClassifiers xsi:type="ecore:EClass" name="Action" eSuperTypes="#//Attack"/>
  <eClassifiers xsi:type="ecore:EClass" name="ThreatAgent" eSuperTypes="odeBase.ecore#//BaseElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="skillLevel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="motivation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anonymityDesire" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attackerGoals" upperBound="-1"
        eType="#//AttackerGoal" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Human" eSuperTypes="#//ThreatAgent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//Action"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NonHuman" eSuperTypes="#//ThreatAgent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="payloads" upperBound="-1"
        eType="#//Payload"/>
  </eClassifiers>
</ecore:EPackage>
