<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="integration" nsURI="http://www.deis-project.eu/ode/integration"
    nsPrefix="integration_">
  <eClassifiers xsi:type="ecore:EClass" name="DDIPackage" eSuperTypes="odeBase.ecore#//BaseElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="odeProductPackages" upperBound="-1"
        eType="#//ODEProductPackage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assuranceCasePackages"
        upperBound="-1" eType="ecore:EClass assurancecase.ecore#//AssuranceCasePackage"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ODEProductPackage" abstract="true" eSuperTypes="odeBase.ecore#//BaseElement"/>
</ecore:EPackage>
