<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="odeBase" nsURI="http://www.deis-project.eu/ode/base" nsPrefix="odeBase_">
  <eClassifiers xsi:type="ecore:EClass" name="BaseElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="keyValueMaps" upperBound="-1"
        eType="#//KeyValueMap" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TimeUnit">
    <eLiterals name="Millisecond"/>
    <eLiterals name="Second" value="1"/>
    <eLiterals name="Minute" value="2"/>
    <eLiterals name="Hour" value="3"/>
    <eLiterals name="Day" value="4"/>
    <eLiterals name="Week" value="5"/>
    <eLiterals name="Month" value="6"/>
    <eLiterals name="Year" value="7"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KeyValueMap">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
        eType="#//Value" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Value">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tag" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
